name: Continuous Deployment

on: 
  push:
    branches:
      - master

jobs:
  containerized:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/forumapi:0.1

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.USERNAME_SERVER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          sudo docker stop forumapi-container
          sudo docker rm forumapi-container
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/forumapi-container:0.1

          sudo docker run -d --network=host --restart=always -e PGHOST=${{ secrets.PGHOST_PROD }} -e PGPORT=${{ secrets.PGPORT }} -e PGUSER=${{ secrets.PGUSER }} -e PGPASSWORD=${{ secrets.PGPASSWORD }} -e PGDATABASE=${{ secrets.PGDATABASE }} -e ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }} -e REFRESH_TOKEN_KEY=${{ REFRESH_TOKEN_KEY.PGDATABASE }} --name forumapi-cointainer ${{ secrets.DOCKERHUB_USERNAME }}/forumapi:0.1