name: Continuous Integration
 
on: 
  pull_request:
    branches:
      - master
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: ['14.x']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
   
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm run test
      env:
        CI: true
        PORT: ${{ secrets.PORT }}
        PORT_TEST: ${{ secrets.PORT_TEST }}
        PGHOST: ${{ secrets.PGHOST }}
        PGPORT: ${{ secrets.PGPORT }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
        PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
        ACCESS_TOKEN_AGE: 3000